# Generated by Django 2.2.12 on 2021-05-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_md5',
            field=models.CharField(default='', max_length=50),
        ),
    ]
