# Generated by Django 2.2.12 on 2021-06-07 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mouldlist',
            fields=[
                ('mouldid', models.BigAutoField(primary_key=True, serialize=False)),
                ('mouldname', models.CharField(max_length=50)),
                ('mouldjson', models.TextField(max_length=200)),
                ('create_date', models.CharField(max_length=20)),
                ('username', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
