# Generated by Django 2.2.12 on 2021-05-19 10:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mouldlist',
            fields=[
                ('mouldid', models.BigAutoField(primary_key=True, serialize=False)),
                ('mouldname', models.CharField(max_length=50)),
                ('mouldjson', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('userid', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
