const router = require('koa-router')()
const HomeController = require('./controller/email')
module.exports = (app) => {
  router.post( '/emailapi/getCode', HomeController.getCode )
  router.post('/emailapi/checkCode', HomeController.checkCode)
  router.post('/faceapi/clock', HomeController.clock)
  router.post('/faceapi/upload',HomeController.upface)
  router.post('/faceapi/getface',HomeController.getface)
  router.post('/faceapi/delface',HomeController.delface)
  router.post('/faceapi/getkaoqin',HomeController.getkaoqin)
  router.post('/faceapi/datekaoqin',HomeController.datekaoqin)
  router.post('/faceapi/timekaoqin',HomeController.timekaoqin)
  router.post('/faceapi/BMlist',HomeController.BMlist)
  router.post('/faceapi/guize',HomeController.guize)
  router.post('/faceapi/getuser',HomeController.getuser)
  router.post('/faceapi/getlist',HomeController.getList)
  router.post('/faceapi/delguize',HomeController.delguize)
  app.use(router.routes())
     .use(router.allowedMethods())
}
