# Generated by Django 2.2.12 on 2021-07-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('faceid', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('set', models.CharField(blank=True, db_column='Set', max_length=255, null=True)),
                ('bm', models.CharField(blank=True, db_column='BM', max_length=50, null=True)),
            ],
            options={
                'db_table': 'face',
            },
        ),
        migrations.CreateModel(
            name='Guize',
            fields=[
                ('bm', models.CharField(blank=True, db_column='BM', max_length=50, null=True, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('bmid', models.AutoField(db_column='BMid', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'guize',
            },
        ),
        migrations.CreateModel(
            name='Kaoqin',
            fields=[
                ('id', models.CharField(blank=True, db_column='ID', max_length=255, null=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('nbr', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('bm', models.CharField(blank=True, db_column='BM', max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('deviceno', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime', models.CharField(blank=True, max_length=255, null=True)),
                ('direction', models.CharField(blank=True, max_length=255, null=True)),
                ('nid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'kaoqin',
            },
        ),
    ]
